service: serverless-pdf-creator
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 10

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  patterns:
    - src/templates/**

functions:
  createPdf:
    handler: src/pdf-creator/handler.createPdf
    events:
      - httpApi:
          path: /pdf/create
          method: post
